USE fusion;

INSERT INTO Categories VALUES (1, "Electronics & Computers", 0);
INSERT INTO Categories VALUES (2, "Home Audio & Theater", 1);
INSERT INTO Categories VALUES (3, "Speakers", 2);
INSERT INTO Categories VALUES (4, "Bluetooth", 2);
INSERT INTO Categories VALUES (5, "Bookshelf", 2);
INSERT INTO Categories VALUES (6, "Ceiling & in-wall", 2);
INSERT INTO Categories VALUES (7, "Subwoofers", 2);
INSERT INTO Categories VALUES (8, "Surround sound", 2);
INSERT INTO Categories VALUES (9, "Stereo System components", 1);
INSERT INTO Categories VALUES (10, "Receivers & amplifiers", 9);
INSERT INTO Categories VALUES (11, "Tuners", 9);
INSERT INTO Categories VALUES (12, "Turntables", 9);
INSERT INTO Categories VALUES (13, "Home Audio Accessories", 1);
INSERT INTO Categories VALUES (14, "Cables", 13);
INSERT INTO Categories VALUES (15, "Speaker accessories", 13);
INSERT INTO Categories VALUES (16, "Home entertainment furniture", 13);
INSERT INTO Categories VALUES (17, "Cell Phones & Accessories", 1);
INSERT INTO Categories VALUES (18, "Cell Phones", 17);
INSERT INTO Categories VALUES (19, "Cases", 17);
INSERT INTO Categories VALUES (20, "Connected Devices", 1);
INSERT INTO Categories VALUES (21, "Mobile hotspots", 20);
INSERT INTO Categories VALUES (22, "Smart watches", 20);
INSERT INTO Categories VALUES (23, "Wearable tech", 20);
INSERT INTO Categories VALUES (24, "Accessories", 1);
INSERT INTO Categories VALUES (25, "Batteries", 24);
INSERT INTO Categories VALUES (26, "Chargers", 24);
INSERT INTO Categories VALUES (27, "Mounts", 24);
INSERT INTO Categories VALUES (28, "Screen protectors", 24);
INSERT INTO Categories VALUES (29, "Headphones", 1);
INSERT INTO Categories VALUES (30, "Earbud headphones", 29);
INSERT INTO Categories VALUES (31, "Over-ear headphones", 29);
INSERT INTO Categories VALUES (32, "On-ear headphones", 29);
INSERT INTO Categories VALUES (33, "Noise-cancelling headphones", 29);
INSERT INTO Categories VALUES (34, "Computers & Tablets", 1);
INSERT INTO Categories VALUES (35, "Desktops", 34);
INSERT INTO Categories VALUES (36, "Towers", 35);
INSERT INTO Categories VALUES (37, "All-in-ones", 35);
INSERT INTO Categories VALUES (38, "Minis", 35);
INSERT INTO Categories VALUES (39, "Laptops", 34);
INSERT INTO Categories VALUES (40, "Traditional", 39);
INSERT INTO Categories VALUES (41, "2-in-1", 39);
INSERT INTO Categories VALUES (42, "Tablets", 34);
INSERT INTO Categories VALUES (43, "Computer Parts & Components", 1);
INSERT INTO Categories VALUES (44, "Processors", 43);
INSERT INTO Categories VALUES (45, "Motherboards", 43);
INSERT INTO Categories VALUES (46, "Graphics Cards", 43);
INSERT INTO Categories VALUES (47, "Storage", 43);
INSERT INTO Categories VALUES (48, "Memory", 43);
INSERT INTO Categories VALUES (49, "Power Supplies & Fans", 43);
INSERT INTO Categories VALUES (50, "Software", 43);
INSERT INTO Categories VALUES (51, "Printers & Ink", 1);
INSERT INTO Categories VALUES (52, "Inkjet printers", 51);
INSERT INTO Categories VALUES (53, "Laser printers", 51);
INSERT INTO Categories VALUES (54, "Label printers", 51);
INSERT INTO Categories VALUES (55, "Clothing, Shoes & Jewelry", 0);
INSERT INTO Categories VALUES (56, "Women", 55);
INSERT INTO Categories VALUES (57, "Clothing", 56);
INSERT INTO Categories VALUES (58, "Dresses", 57);
INSERT INTO Categories VALUES (59, "Tops", 57);
INSERT INTO Categories VALUES (60, "Pants", 57);
INSERT INTO Categories VALUES (61, "Skirts", 57);
INSERT INTO Categories VALUES (62, "Shorts", 57);
INSERT INTO Categories VALUES (63, "Swimsuits", 57);
INSERT INTO Categories VALUES (64, "Coats & jackets", 57);
INSERT INTO Categories VALUES (65, "Shoes", 56);
INSERT INTO Categories VALUES (66, "Athletic", 65);
INSERT INTO Categories VALUES (67, "Boots", 65);
INSERT INTO Categories VALUES (68, "Outdoor", 65);
INSERT INTO Categories VALUES (69, "Sandals", 65);
INSERT INTO Categories VALUES (70, "Slippers", 65);
INSERT INTO Categories VALUES (71, "Jewelry", 56);
INSERT INTO Categories VALUES (72, "Fashion", 71);
INSERT INTO Categories VALUES (73, "Religious", 71);
INSERT INTO Categories VALUES (74, "Handbags & Wallets", 56);
INSERT INTO Categories VALUES (75, "Shoulder Bags", 74);
INSERT INTO Categories VALUES (76, "Wallets", 74);
INSERT INTO Categories VALUES (77, "Watches", 56);
INSERT INTO Categories VALUES (78, "Men", 55);
INSERT INTO Categories VALUES (79, "Clothing", 78);
INSERT INTO Categories VALUES (80, "Shirts", 79);
INSERT INTO Categories VALUES (81, "Pants", 79);
INSERT INTO Categories VALUES (82, "Shorts", 79);
INSERT INTO Categories VALUES (83, "Swim", 79);
INSERT INTO Categories VALUES (84, "Shoes", 78);
INSERT INTO Categories VALUES (85, "Athletic", 84);
INSERT INTO Categories VALUES (86, "Boots", 84);
INSERT INTO Categories VALUES (87, "Sandals", 84);
INSERT INTO Categories VALUES (88, "Sneakers", 84);
INSERT INTO Categories VALUES (89, "Jewelry", 78);
INSERT INTO Categories VALUES (90, "Watches", 78);
INSERT INTO Categories VALUES (91, "Girls", 55);
INSERT INTO Categories VALUES (92, "Clothing", 91);
INSERT INTO Categories VALUES (93, "Dresses", 92);
INSERT INTO Categories VALUES (94, "Tops", 92);
INSERT INTO Categories VALUES (95, "Pants", 92);
INSERT INTO Categories VALUES (96, "Skirts", 92);
INSERT INTO Categories VALUES (97, "Shorts", 92);
INSERT INTO Categories VALUES (98, "Swimsuits", 92);
INSERT INTO Categories VALUES (99, "Coats & jackets", 92);
INSERT INTO Categories VALUES (100, "Shoes", 91);
INSERT INTO Categories VALUES (101, "Athletic", 100);
INSERT INTO Categories VALUES (102, "Boots", 100);
INSERT INTO Categories VALUES (103, "Outdoor", 100);
INSERT INTO Categories VALUES (104, "Sandals", 100);
INSERT INTO Categories VALUES (105, "Slippers", 100);
INSERT INTO Categories VALUES (106, "Jewelry", 91);
INSERT INTO Categories VALUES (107, "Fashion", 106);
INSERT INTO Categories VALUES (108, "Religious", 106);
INSERT INTO Categories VALUES (109, "Handbags & Wallets", 91);
INSERT INTO Categories VALUES (110, "Shoulder Bags", 109);
INSERT INTO Categories VALUES (111, "Wallets", 109);
INSERT INTO Categories VALUES (112, "Watches", 91);
INSERT INTO Categories VALUES (113, "Boys", 55);
INSERT INTO Categories VALUES (114, "Clothing", 113);
INSERT INTO Categories VALUES (115, "Shirts", 114);
INSERT INTO Categories VALUES (116, "Pants", 114);
INSERT INTO Categories VALUES (117, "Shorts", 114);
INSERT INTO Categories VALUES (118, "Swim", 114);
INSERT INTO Categories VALUES (119, "Shoes", 113);
INSERT INTO Categories VALUES (120, "Athletic", 119);
INSERT INTO Categories VALUES (121, "Boots", 119);
INSERT INTO Categories VALUES (122, "Sandals", 119);
INSERT INTO Categories VALUES (123, "Sneakers", 119);
INSERT INTO Categories VALUES (124, "Jewelry", 113);
INSERT INTO Categories VALUES (125, "Watches", 113);
INSERT INTO Categories VALUES (126, "Luggage", 55);
INSERT INTO Categories VALUES (127, "Backpacks", 126);
INSERT INTO Categories VALUES (128, "Briefcases", 126);
INSERT INTO Categories VALUES (129, "Travel Duffels", 126);
INSERT INTO Categories VALUES (130, "Luggage", 126);
INSERT INTO Categories VALUES (131, "Home & Garden", 0);
INSERT INTO Categories VALUES (132, "Kitchen & Dining", 131);
INSERT INTO Categories VALUES (133, "Bakeware", 132);
INSERT INTO Categories VALUES (134, "Bakeware Sets", 133);
INSERT INTO Categories VALUES (135, "Mixing bowls", 133);
INSERT INTO Categories VALUES (136, "Cookware", 132);
INSERT INTO Categories VALUES (137, "Skillets", 136);
INSERT INTO Categories VALUES (138, "Pot racks", 136);
INSERT INTO Categories VALUES (139, "Saucepans", 136);
INSERT INTO Categories VALUES (140, "Sauté pans", 136);
INSERT INTO Categories VALUES (141, "Steamers", 136);
INSERT INTO Categories VALUES (142, "Cutlery", 132);
INSERT INTO Categories VALUES (143, "Knife sets", 142);
INSERT INTO Categories VALUES (144, "Cutting boards", 142);
INSERT INTO Categories VALUES (145, "Shears", 142);
INSERT INTO Categories VALUES (146, "Knife sharpeners", 142);
INSERT INTO Categories VALUES (147, "Small appliances", 132);
INSERT INTO Categories VALUES (148, "Slow cookers", 147);
INSERT INTO Categories VALUES (149, "Microwave ovens", 147);
INSERT INTO Categories VALUES (150, "Blenders", 147);
INSERT INTO Categories VALUES (151, "Juicers", 147);
INSERT INTO Categories VALUES (152, "Deep fryers", 147);
INSERT INTO Categories VALUES (153, "Coffee, tea & espresso appliances", 147);
INSERT INTO Categories VALUES (154, "Water coolers & filters", 132);
INSERT INTO Categories VALUES (155, "Faucet filters", 154);
INSERT INTO Categories VALUES (156, "Pitcher filters", 154);
INSERT INTO Categories VALUES (157, "Water coolers", 154);
INSERT INTO Categories VALUES (158, "Storage & organization", 132);
INSERT INTO Categories VALUES (159, "Food storage", 158);
INSERT INTO Categories VALUES (160, "Travel containers", 158);
INSERT INTO Categories VALUES (161, "Cabinet & drawer organization", 158);
INSERT INTO Categories VALUES (162, "Furniture", 131);
INSERT INTO Categories VALUES (163, "Bedroom", 162);
INSERT INTO Categories VALUES (164, "Beds, frames & bases", 163);
INSERT INTO Categories VALUES (165, "Dressers", 163);
INSERT INTO Categories VALUES (166, "Futons", 163);
INSERT INTO Categories VALUES (167, "Nightstands", 163);
INSERT INTO Categories VALUES (168, "Living room", 162);
INSERT INTO Categories VALUES (169, "Chairs", 168);
INSERT INTO Categories VALUES (170, "Tables", 168);
INSERT INTO Categories VALUES (171, "Sofas & couches", 168);
INSERT INTO Categories VALUES (172, "Kitchen & Dining", 162);
INSERT INTO Categories VALUES (173, "Chairs", 172);
INSERT INTO Categories VALUES (174, "China cabinets", 172);
INSERT INTO Categories VALUES (175, "Pantries", 172);
INSERT INTO Categories VALUES (176, "Tables", 172);
INSERT INTO Categories VALUES (177, "Home bar", 162);
INSERT INTO Categories VALUES (178, "Barstools", 177);
INSERT INTO Categories VALUES (179, "Wine cabinets", 177);
INSERT INTO Categories VALUES (180, "Bathroom", 162);
INSERT INTO Categories VALUES (181, "Mirrors", 180);
INSERT INTO Categories VALUES (182, "Medicine cabinets", 180);
INSERT INTO Categories VALUES (183, "Over-toilet storage", 180);
INSERT INTO Categories VALUES (184, "Lounge & recreation", 162);
INSERT INTO Categories VALUES (185, "Video game chairs", 184);
INSERT INTO Categories VALUES (186, "Bean bags", 184);
INSERT INTO Categories VALUES (187, "Game & card tables", 184);
INSERT INTO Categories VALUES (188, "Bedding & Bath", 131);
INSERT INTO Categories VALUES (189, "Bed Pillows", 188);
INSERT INTO Categories VALUES (190, "Shower curtains", 188);
INSERT INTO Categories VALUES (191, "Bath rugs", 188);
INSERT INTO Categories VALUES (192, "Towels", 188);
INSERT INTO Categories VALUES (193, "Bedspreads", 188);
INSERT INTO Categories VALUES (194, "Mattresses", 188);
INSERT INTO Categories VALUES (195, "Patio, Lawn & Garden", 131);
INSERT INTO Categories VALUES (196, "Gardening & lawn care", 195);
INSERT INTO Categories VALUES (197, "Fertilizer", 196);
INSERT INTO Categories VALUES (198, "Gloves & protective gear", 196);
INSERT INTO Categories VALUES (199, "Pest control", 196);
INSERT INTO Categories VALUES (200, "Pots & planters", 196);
INSERT INTO Categories VALUES (201, "Benches & tables", 196);
INSERT INTO Categories VALUES (202, "Grills & outdoor cooking", 195);
INSERT INTO Categories VALUES (203, "Grills", 202);
INSERT INTO Categories VALUES (204, "Fuel & fire starters", 202);
INSERT INTO Categories VALUES (205, "Snow removal", 195);
INSERT INTO Categories VALUES (206, "Snow blowers", 205);
INSERT INTO Categories VALUES (207, "Snow plows", 205);
INSERT INTO Categories VALUES (208, "Snow shovels", 205);
INSERT INTO Categories VALUES (209, "Snow blower accessories", 205);
INSERT INTO Categories VALUES (210, "Outdoor Storage", 195);
INSERT INTO Categories VALUES (211, "Sheds", 210);
INSERT INTO Categories VALUES (212, "Deck boxes", 210);
INSERT INTO Categories VALUES (213, "Carports", 210);
INSERT INTO Categories VALUES (214, "Plants, seeds & bulbs", 195);
INSERT INTO Categories VALUES (215, "Pet Supplies", 131);
INSERT INTO Categories VALUES (216, "Dogs", 215);
INSERT INTO Categories VALUES (217, "Food", 216);
INSERT INTO Categories VALUES (218, "Treats", 216);
INSERT INTO Categories VALUES (219, "Beds", 216);
INSERT INTO Categories VALUES (220, "Toys", 216);
INSERT INTO Categories VALUES (221, "Collars & leashes", 216);
INSERT INTO Categories VALUES (222, "Cats", 215);
INSERT INTO Categories VALUES (223, "Food", 222);
INSERT INTO Categories VALUES (224, "Treats", 222);
INSERT INTO Categories VALUES (225, "Toys", 222);
INSERT INTO Categories VALUES (226, "Carriers", 222);
INSERT INTO Categories VALUES (227, "Collars", 222);
INSERT INTO Categories VALUES (228, "Fish & aquatic pets", 215);
INSERT INTO Categories VALUES (229, "Food", 228);
INSERT INTO Categories VALUES (230, "Aquarium accessories", 228);
INSERT INTO Categories VALUES (231, "Birds", 215);
INSERT INTO Categories VALUES (232, "Food", 231);
INSERT INTO Categories VALUES (233, "Treats", 231);
INSERT INTO Categories VALUES (234, "Cages", 231);
INSERT INTO Categories VALUES (235, "Lamps & Light Fixtures", 131);
INSERT INTO Categories VALUES (236, "Lamps & shades", 235);
INSERT INTO Categories VALUES (237, "Outdoor lighting", 235);
INSERT INTO Categories VALUES (238, "Ceiling lights", 235);
INSERT INTO Categories VALUES (239, "Ceiling fans", 235);
INSERT INTO Categories VALUES (240, "Wall lights", 235);
INSERT INTO Categories VALUES (241, "Hardware", 131);
INSERT INTO Categories VALUES (242, "Door Hardware", 241);
INSERT INTO Categories VALUES (243, "Garage & Gate", 241);
INSERT INTO Categories VALUES (244, "Cabinet & Furniture", 241);
INSERT INTO Categories VALUES (245, "Window", 241);
INSERT INTO Categories VALUES (246, "Adhesive & Sealers", 241);
INSERT INTO Categories VALUES (247, "Painting Supplies", 241);
INSERT INTO Categories VALUES (248, "Weatherproofing", 241);
INSERT INTO Categories VALUES (249, "Power & Hand Tools", 131);
INSERT INTO Categories VALUES (250, "Power tools", 249);
INSERT INTO Categories VALUES (251, "Hand tools", 249);
INSERT INTO Categories VALUES (252, "Woodworking", 249);
INSERT INTO Categories VALUES (253, "Measuring & Layout tools", 249);
INSERT INTO Categories VALUES (254, "Air tools & compressors", 249);
INSERT INTO Categories VALUES (255, "Sports & Outdoors", 0);
INSERT INTO Categories VALUES (256, "Exercise & Fitness", 255);
INSERT INTO Categories VALUES (257, "Cardio Equipment", 256);
INSERT INTO Categories VALUES (258, "Treadmills", 257);
INSERT INTO Categories VALUES (259, "Exercise bikes", 257);
INSERT INTO Categories VALUES (260, "Elliptical machines", 257);
INSERT INTO Categories VALUES (261, "Home Gym", 256);
INSERT INTO Categories VALUES (262, "Free weights", 256);
INSERT INTO Categories VALUES (263, "Yoga", 256);
INSERT INTO Categories VALUES (264, "Mats", 263);
INSERT INTO Categories VALUES (265, "Towels", 263);
INSERT INTO Categories VALUES (266, "Blocks", 263);
INSERT INTO Categories VALUES (267, "Hunting & Fishing", 255);
INSERT INTO Categories VALUES (268, "Hunting", 267);
INSERT INTO Categories VALUES (269, "Optics", 268);
INSERT INTO Categories VALUES (270, "Guns", 268);
INSERT INTO Categories VALUES (271, "Bows", 268);
INSERT INTO Categories VALUES (272, "Tree stands", 268);
INSERT INTO Categories VALUES (273, "Hunting knives", 268);
INSERT INTO Categories VALUES (274, "Fishing", 267);
INSERT INTO Categories VALUES (275, "Rods", 274);
INSERT INTO Categories VALUES (276, "Reels", 274);
INSERT INTO Categories VALUES (277, "Fishing Line", 274);
INSERT INTO Categories VALUES (278, "Fish finders", 274);
INSERT INTO Categories VALUES (279, "Tactical & personal defense", 267);
INSERT INTO Categories VALUES (280, "Pepper spray", 279);
INSERT INTO Categories VALUES (281, "Tactical vests", 279);
INSERT INTO Categories VALUES (282, "Protective body equipment", 279);
INSERT INTO Categories VALUES (283, "Camping & Hiking", 255);
INSERT INTO Categories VALUES (284, "Tents & Shelter", 283);
INSERT INTO Categories VALUES (285, "Sleeping Bags & camp bedding", 283);
INSERT INTO Categories VALUES (286, "Hydration", 283);
INSERT INTO Categories VALUES (287, "Canteens", 286);
INSERT INTO Categories VALUES (288, "Flasks", 286);
INSERT INTO Categories VALUES (289, "Knives & tools", 283);
INSERT INTO Categories VALUES (290, "Navigation", 283);
INSERT INTO Categories VALUES (291, "Compasses", 290);
INSERT INTO Categories VALUES (292, "Gps trackers", 290);
INSERT INTO Categories VALUES (293, "Safety & survival", 283);
INSERT INTO Categories VALUES (294, "First-aid kits", 293);
INSERT INTO Categories VALUES (295, "Whistles", 293);
INSERT INTO Categories VALUES (296, "Lighters", 293);
INSERT INTO Categories VALUES (297, "Golf", 255);
INSERT INTO Categories VALUES (298, "Balls", 297);
INSERT INTO Categories VALUES (299, "Bags", 297);
INSERT INTO Categories VALUES (300, "Complete Sets", 297);
INSERT INTO Categories VALUES (301, "Clubs", 297);
INSERT INTO Categories VALUES (302, "Rangefinders", 297);
INSERT INTO Categories VALUES (303, "Training equipment", 297);
INSERT INTO Categories VALUES (304, "Team Sports", 255);
INSERT INTO Categories VALUES (305, "Baseball & softball", 304);
INSERT INTO Categories VALUES (306, "Baseballs", 305);
INSERT INTO Categories VALUES (307, "Softballs", 305);
INSERT INTO Categories VALUES (308, "Bats", 305);
INSERT INTO Categories VALUES (309, "Gloves", 305);
INSERT INTO Categories VALUES (310, "Cleats", 305);
INSERT INTO Categories VALUES (311, "Basketball", 304);
INSERT INTO Categories VALUES (312, "Football", 304);
INSERT INTO Categories VALUES (313, "Helmets", 312);
INSERT INTO Categories VALUES (314, "Pads", 312);
INSERT INTO Categories VALUES (315, "Cleats", 312);
INSERT INTO Categories VALUES (316, "Footballs", 312);
INSERT INTO Categories VALUES (317, "Soccer", 304);
INSERT INTO Categories VALUES (318, "Cleats", 317);
INSERT INTO Categories VALUES (319, "Shin guards", 317);
INSERT INTO Categories VALUES (320, "Soccer balls", 317);
INSERT INTO Categories VALUES (321, "Lacrosse", 304);
INSERT INTO Categories VALUES (322, "Pads", 321);
INSERT INTO Categories VALUES (323, "Field equipment", 321);
INSERT INTO Categories VALUES (324, "Balls", 321);
INSERT INTO Categories VALUES (325, "Cleats", 321);
INSERT INTO Categories VALUES (326, "Ice Hockey", 304);
INSERT INTO Categories VALUES (327, "Pucks", 326);
INSERT INTO Categories VALUES (328, "Player equipment", 326);
INSERT INTO Categories VALUES (329, "Volleyball", 304);
INSERT INTO Categories VALUES (330, "Court equipment", 329);
INSERT INTO Categories VALUES (331, "Volleyballs", 329);
INSERT INTO Categories VALUES (332, "Water Sports", 255);
INSERT INTO Categories VALUES (333, "Canoeing", 332);
INSERT INTO Categories VALUES (334, "Kayaking", 332);
INSERT INTO Categories VALUES (335, "Surfing", 332);
INSERT INTO Categories VALUES (336, "Diving & Snorkeling", 332);
INSERT INTO Categories VALUES (337, "Winter Sports", 255);
INSERT INTO Categories VALUES (338, "Skiing", 337);
INSERT INTO Categories VALUES (339, "Snowboarding", 337);
INSERT INTO Categories VALUES (340, "Ice skating", 337);
INSERT INTO Categories VALUES (341, "Snowmobiling", 337);
INSERT INTO Categories VALUES (342, "Entertainment", 0);
INSERT INTO Categories VALUES (343, "Movies & TV", 342);
INSERT INTO Categories VALUES (344, "Blu-ray", 343);
INSERT INTO Categories VALUES (345, "Movies", 343);
INSERT INTO Categories VALUES (346, "Tv Shows", 343);
INSERT INTO Categories VALUES (347, "CDs & Vinyl", 342);
INSERT INTO Categories VALUES (348, "Vinyl Records", 347);
INSERT INTO Categories VALUES (349, "Digital music", 347);
INSERT INTO Categories VALUES (350, "CDs", 347);
INSERT INTO Categories VALUES (351, "Musical Instruments", 342);
INSERT INTO Categories VALUES (352, "Guitars", 351);
INSERT INTO Categories VALUES (353, "Amplifiers & effects", 351);
INSERT INTO Categories VALUES (354, "Keyboards", 351);
INSERT INTO Categories VALUES (355, "Brass instruments", 351);
INSERT INTO Categories VALUES (356, "Stringed instruments", 351);
INSERT INTO Categories VALUES (357, "Studio recording equipment", 342);
INSERT INTO Categories VALUES (358, "Video Games", 342);
INSERT INTO Categories VALUES (359, "Systems", 358);
INSERT INTO Categories VALUES (360, "Games", 358);
INSERT INTO Categories VALUES (361, "Controllers", 358);
INSERT INTO Categories VALUES (362, "Accessories", 358);
