

/* --------------------- Populate sale_items Table --------------------------*/


INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (1, "Deepwater Horizon", 1, 1500, 2000, 3, 342, "Mark Wahlberg", 1, "From the director of Lone Survivor");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (2, "Arrival", 1, 1300, 2000, 3, 342, "Amy Adams", 1, "Mysterious spacecraft land across the globe.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (3, "The Departed", 1, 1500, 2000, 4, 342, "Leonardo DiCaprio", 1, "Martin Scorsese's crime drama The Departed is set in South Boston where the state police force is waging an all-out war to take down the city's top organized crime ring. ");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (4, "Dirty Grandpa", 1, 1400, 2000, 3, 342, "Robert DeNiro, Zac Efron", 1, "A hilarious and outrageous raunchy comedy starring Zac Efron and Robert DeNiro that proves you're only as young as you feel! ");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (5, "The Sandlot", 1, 1200, 2000, 5, 342, "Art LaFleur, Tom Guiry", 1, "Nine boys become a team and their leader becomes a legend by confronting the terrifying mystery beyond the right field wall");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (6, "Panasonic In-Ear Headphones", 2, 9250, 9000, 10, 30, "Black ultra soft", 1, "Black ultra-soft ErgoFit in-ear earbud headphones conform instantly to your ears");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (7, "Beats Studio Wireless Over-Ear Headphones", 2, 22999, 25000, 3, 31, "Beats - Titanium", 1, "Pair and play with your Bluetooth device with 30 foot range.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (8, "Sony Noise Cancelling Headphones", 2, 3450, 4000, 4, 33, "Black On-Ear headphones", 1, "Noise-isolating headphones");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (9, "BoomTouch Wireless Touch Portable Speaker", 2, 2499, 2600, 2, 3, "Wireless speaker", 1, "Clear, Crisp, High-Quality Sound that will be sure to amaze you & everyone else! ");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (10, "ZOEE Outdoor Portable Stereo Speaker", 2, 1799, 2000, 6, 3, "Bluetook speaker", 1, "Distinct mids and highs from our two precision acoustic drivers delivers excellent stereo sound and enhanced bass from our proprietary Subwoofer design.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (11, "Sony Bookshelf Speaker", 2, 1999, 2100, 6, 5, "Bookshelf Speaker", 1, "Great speaker for a large livingroom!");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (12, "Bose In-wall Speaker", 2, 4500, 5000, 2, 6, "In-wall Speaker", 1, "Easy install and great for home theatres!");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (13, "Gorilla 12 Subwoofers", 2, 19999, 21000, 4, 7, "Subwoofers", 1, "Easy install car subwoofers.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (14, "Spencers Surround Sound Speakers", 2, 42999, 44000, 3, 8, "Surround sound speakers", 1, "Surround sound speakers that will blow your mind!");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (15, "Sony DZE3 Receiver", 2, 9999, 1100, 2, 9, "Receiver", 2, "A great receiver to connect to any existing speakers.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (16, "Song XEE44 Amplifier", 2, 25999, 27000, 5, 10, "Amplifier", 1, "An amp that will blow your mind!");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (17, "Pro Brand HDTV Tuner/Receiver ", 2, 23000, 25000, 3, 11, "Tuner",  1, "Fully integrated high-definition tuner/receiver with selectable 1080i, 720p, and 480p outputs");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (18, "Audio Technica Belt-Drive Stereo Turntable", 2, 20000, 21000, 2, 12, "Turntable", 1, "Great for mixing!");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (19, "Jensen JTA-230", 2, 4344, 4500, 2, 12, "Turntable", 2, "Belt Driven 3-Speed Stereo Turntable 33/45/78 RPM with Stereo Speaker System ");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (20, "UGREEN 3.5mm to 2RCA Audio Auxiliary", 2, 699, 800, 1, 13, "Accessory", 1, "Ugreen 3.5mm to 2RCA Stereo Audio Splitter Cable connects your 3.5mm audio device like a Smartphone.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (21, "AmazonBasics 16-Gauge Speaker Wire", 2, 1034, 1200, 6, 13, "Wire", 1, "100 Feet of 16-gauge speaker wire.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (22, "Samsung Galaxy J7 No Contract Phone", 2, 14799, 16000, 4, 18, "Cell Phone", 1, "White Samsung Galaxy J7 with no contract needed.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (23, "LG Phoenix 2 K371 Mobile 4g LTE GSM", 2, 6900, 7500, 2, 18, "Cell Phone", 1, "5-Inch HD, 16GB, 8MP LED Flash + 5MP, Android 6.0 Locked AT&T Prepaid, U.S. Warranty.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (24, "Speck Products Presidio Grip Cell Phone Case", 2, 2299, 2400, 6, 19, "Phone Case", 1, "iPhone 7 Plus - Black/Black Case.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (25, "OtterBox DEFENDER SERIES Case", 2, 3499, 3600, 3, 19, "Phone Case", 1, "iPhone 7 Plus Case.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (26, "CM4 iPhone 7 Wallet Case", 2, 2999, 3200, 8, 19, "Phone Case", 1, "Q Card Case for iPhone 7.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (26, "Huawei E5573s-320 Unlocked 150 Mbps 4G LTE", 2, 9999, 1100, 7, 21, "Mobile hotspot", 1, "43.2 Mpbs 3G Mobile WiFi");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (27, "Fitbit Blaze Smart Fitness Watch", 2, 19895, 20000, 4, 22, "Smart watch", 2, "Fitbit Blaze syncs automatically and wirelessly to 200+ leading iOS, Android and Windows devices using Bluetooth 4.0 wireless technology.");
INSERT INTO sale_items (id, name, seller, price, reservePrice, quantity, category, detailedDescriptionURL, typeOfSale, description) VALUES (28, "Anker Astro E1", 2, 1599, 1700, 3, 22, "Charger", 2, "The Anker Advantage: Join the 10 million+ powered by our leading technology. ");
