UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/deepwaterhorizon' WHERE `id`='1' and`detailedDescriptionURL`='Mark Wahlberg';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/Arrival' WHERE `id`='2' and`detailedDescriptionURL`='Amy Adams';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/thedeparted' WHERE `id`='3' and`detailedDescriptionURL`='Leonardo DiCaprio';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/dirtygrampa' WHERE `id`='4' and`detailedDescriptionURL`='Robert DeNiro, Zac Efron';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/thesandlot' WHERE `id`='5' and`detailedDescriptionURL`='Art LaFleur, Tom Guiry';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/panasonic' WHERE `id`='6' and`detailedDescriptionURL`='Black ultra soft';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/BeatsStudioWirelessOver-EarHeadphones' WHERE `id`='7' and`detailedDescriptionURL`='Beats - Titanium';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/sonyHP' WHERE `id`='8' and`detailedDescriptionURL`='Black On-Ear headphones';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/BoomTouchWirelessTouchPortableSpeaker' WHERE `id`='9' and`detailedDescriptionURL`='Wireless speaker';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/zoee' WHERE `id`='10' and`detailedDescriptionURL`='Bluetook speaker';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/sonybookshelf' WHERE `id`='11' and`detailedDescriptionURL`='Bookshelf Speaker';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/boseinwall' WHERE `id`='12' and`detailedDescriptionURL`='In-wall Speaker';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/Gorilla12Subwoofers' WHERE `id`='13' and`detailedDescriptionURL`='Subwoofers';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/surroundsound' WHERE `id`='14' and`detailedDescriptionURL`='Surround sound speakers';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/dze3rec' WHERE `id`='15' and`detailedDescriptionURL`='Receiver';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/sonyamp' WHERE `id`='16' and`detailedDescriptionURL`='Amplifier';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/hdtvtuner' WHERE `id`='17' and`detailedDescriptionURL`='Tuner';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/AudioTechnicaBelt-DriveStereoTurntable ' WHERE `id`='18' and`detailedDescriptionURL`='Turntable';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/JensenJTA-230' WHERE `id`='19' and`detailedDescriptionURL`='Turntable';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/2rca' WHERE `id`='20' and`detailedDescriptionURL`='Accessory';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/AmazonBasic16-GaugeSpeakerWire' WHERE `id`='21' and`detailedDescriptionURL`='Wire';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/gs6' WHERE `id`='22' and`detailedDescriptionURL`='Cell Phone';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/lgphone' WHERE `id`='23' and`detailedDescriptionURL`='Cell Phone';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/spec' WHERE `id`='24' and`detailedDescriptionURL`='Phone Case';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/otter' WHERE `id`='25' and`detailedDescriptionURL`='Phone Case';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/Huawei' WHERE `id`='26' and`detailedDescriptionURL`='Mobile hotspot';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/wallet' WHERE `id`='26' and`detailedDescriptionURL`='Phone Case';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/fitbitBlaze' WHERE `id`='27' and`detailedDescriptionURL`='Smart watch';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='images/anker' WHERE `id`='28' and`detailedDescriptionURL`='Charger';
UPDATE `fusion`.`sale_items` SET `detailedDescriptionURL`='' WHERE `id`='30' and`detailedDescriptionURL`='Brand new phone';
UPDATE `fusion`.`sale_items` SET `description`='' WHERE `id`='31' and`detailedDescriptionURL`='sdfgasdg';
